public with sharing class ApiCepJson {
    
    public class DadosEndereco {
        @auraenabled
        public string code;

        @auraenabled
        public string state;

        @auraenabled
        public string city;

        @auraenabled
        public string district;

        @auraenabled
        public string address;

        // @auraenabled
        // public string status;

        // @auraenabled
        // public string ok;
        
        // @auraenabled
        // public string statusText;
    }
}
